// common
const UPDATE_LOADING = 'UPDATE_LOADING'
const UPDATE_LIST = 'UPDATE_LIST'
const UPDATE_ROUTER_MENU = 'UPDATE_ROUTER_MENU'

// login, logout
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const UPDATE_TOKEN = 'UPDATE_TOKEN'
const UPDATE_PERMISSIONS = 'UPDATE_PERMISSIONS'

export {
  UPDATE_LOADING,
  UPDATE_LIST,
  UPDATE_ROUTER_MENU,
  LOGIN,
  LOGOUT,
  UPDATE_TOKEN,
  UPDATE_PERMISSIONS
}